### ISSUE TITLE
Instrucciones

### ISSUE THREAD

**Issue by AngelicaMVG** [muktek/build--gen-project-scss#1]
- la ultima instrucción: sudo chmod u+x /usr/local/bin/watch-scss /usr/local/bin/gen-project-scss
me funciono escribiéndola así :
- sudo chmod u+x watch-scss.sh gen-project-scss

**Comment by tphdev** [comment]
good catch! I changed the README.md to install as: 

```
curl https://raw.githubusercontent.com/muktek/build--gen-project-scss/master/watch-scss.sh > /usr/local/bin/watch-scss

```
