### ISSUE TITLE
Normalize

### ISSUE THREAD

**Issue by AngelicaMVG** [muktek/build--gen-project-scss#2]
- No descarga normalize, aparece esto en terminal:
/usr/local/bin/gen-project-scss: line 40: https://raw.githubusercontent.com/necolas/normalize.css/master/normalize.css: No such file or directory

**Comment by tphdev** [comment]
Gracias! Cambie el `.sh`archive en mi compu pero no en el repo!

Ya tenemos esto en `gen-project-scss.sh`:
```
curl https://cdnjs.cloudflare.com/ajax/libs/normalize/7.0.0/normalize.min.css > ./scss/imports/_normalize.scss
```
